# frozen_string_literal: true

# Writes site/themes.js: the built-in themes as the colours the landing page (site/)
# is drawn in, so its theme switcher shows the same themes the app has.
#
#   bin/rails runner script/site_themes.rb

TOOL_HUES = { "mail" => "blue", "board" => "orange", "docs" => "purple", "chat" => "green",
              "todos" => "pink", "files" => "cyan", "calendar" => "red", "room" => "yellow" }.freeze

themes = Theme.all.map do |theme|
  token = ->(name) { theme.tokens.fetch("--color-#{name}") }
  page = Theme::Color.new(token.("background"))
  dark = theme.dark?

  vars = {
    "--bg" => dark ? token.("background") : token.("background-secondary"),
    "--bg-elevated" => dark ? token.("background-secondary") : token.("background"),
    "--bg-card" => dark ? token.("background-secondary") : token.("background"),
    "--bg-card-hover" => token.("background-tertiary"),
    "--bg-subtle" => token.("sidebar-bg"),
    "--text" => token.("text-primary"),
    "--text-secondary" => token.("text-secondary"),
    "--text-tertiary" => token.("text-tertiary"),
    "--border" => token.("border"),
    "--border-light" => token.("border-light"),
    "--accent" => token.("accent"),
    "--accent-hover" => token.("accent-hover"),
    "--accent-subtle" => token.("accent-light"),
    "--accent-solid" => token.("accent-solid"),
    "--on-accent" => token.("text-inverse"),
    "--green" => token.("success"),
    "--green-subtle" => token.("success-light"),
    "--nav-bg" => "rgba(#{page.red}, #{page.green}, #{page.blue}, 0.85)"
  }
  TOOL_HUES.each { |tool, hue| vars["--tool-#{tool}"] = token.("label-#{hue}") }

  { name: theme.name, label: theme.label, mode: theme.mode, vars: vars }
end

File.write Rails.root.join("site/themes.js"), <<~JS
  // The app's built-in themes, as the colours this page is drawn in.
  // Generated by script/site_themes.rb; don't edit by hand.
  window.DOBASE_THEMES = #{"[\n" + themes.map { |theme| "  " + JSON.generate(theme) }.join(",\n") + "\n]"};
JS

puts "Wrote #{themes.size} themes to site/themes.js"
